# Generated by Django 4.2.2 on 2023-07-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='category title')),
                ('slug', models.SlugField(max_length=55, verbose_name='category slug')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='category image')),
                ('is_active', models.BooleanField(verbose_name='Is Featured')),
            ],
        ),
    ]
