# Generated by Django 4.2.2 on 2023-07-10 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdapp', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(verbose_name='Is active'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='product title')),
                ('slug', models.SlugField(max_length=150, verbose_name='product slug')),
                ('product_image', models.ImageField(blank='True', null='True', upload_to='product', verbose_name='product image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(verbose_name='is_active')),
                ('is_featured', models.BooleanField(verbose_name='is_featured')),
                ('productStock', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdapp.category', verbose_name='product category')),
            ],
        ),
    ]
