# Generated by Django 4.2.2 on 2023-07-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdapp', '0003_alter_category_is_active_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatedimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='relimg')),
                ('products', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sdapp.product')),
            ],
        ),
    ]
