# Generated by Django 4.2.2 on 2023-07-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdapp', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quanty',
            new_name='quantity',
        ),
    ]
